## Indepth of Token And embeddings

In [49]:
!nvidia-smi

Sun Feb 15 18:10:12 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.126.09             Driver Version: 580.126.09     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-16GB           On  |   00000000:04:00.0 Off |                  Off |
| N/A   38C    P0             52W /  300W |   15867MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [1]:
# !pip install torch==2.3.1
# !pip install flash_attn==2.5.8

In [9]:
# !pip install flash_attn

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=True,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [3]:
prompt = "Write a short passage on how to avoid LLM in Human life. Be succint in Language.<|assistant|>"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=30
)

# Print the output
print(tokenizer.decode(generation_output[0]))

You are not running the flash-attention implementation, expect numerical differences.


Write a short passage on how to avoid LLM in Human life. Be succint in Language.<|assistant|> To avoid LLM (Low-Level Manufacturing) in human life, prioritize education and skill development. Embrace continuous learning,


##### The last part of text in  is the 30 tokens generated by the model.

#### Let’s print input_ids 

In [5]:
input_ids 

tensor([[14350,   263,  3273, 13382,   373,   920,   304,  4772,   365, 26369,
           297, 12968,  2834, 29889,  1522,  8348,   524,   297, 17088, 29889,
         32001]], device='cuda:0')

In [6]:
for id in input_ids[0]:
   print(tokenizer.decode(id))

Write
a
short
passage
on
how
to
avoid
L
LM
in
Human
life
.
Be
succ
int
in
Language
.
<|assistant|>


#### Examine Raw Model Output

In [8]:
generation_output 

tensor([[14350,   263,  3273, 13382,   373,   920,   304,  4772,   365, 26369,
           297, 12968,  2834, 29889,  1522,  8348,   524,   297, 17088, 29889,
         32001,  1763,  4772,   365, 26369,   313, 29931,   340, 29899, 10108,
          2315,  9765,  3864, 29897,   297,  5199,  2834, 29892,  7536,   277,
           675,  9793,   322, 19911,  5849, 29889,  2812, 13842,  9126,  6509,
         29892]], device='cuda:0')

In [14]:
TF_ENABLE_ONEDNN_OPTS=0 # to aoid Warnings 
print(tokenizer.decode(14350))
print(tokenizer.decode(263))
print(tokenizer.decode([3273, 13382]))
print(tokenizer.decode(373))
print("\n")
print(tokenizer.decode([ 322, 19911,  5849, 29889,]))

Write
a
short passage
on


and skill development.


## Examine Various Tokenizers

In [15]:
text = """

English and CAPITALIZATION

🎵鸟
show_tokens False None elif == >= else: two tabs:" " Three tabs: "   "

12.0*50=600

"""

In [16]:
colors_list = [
    '102;194;165', '252;141;98', '141;160;203', 
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' + 
            tokenizer.decode(t) + 
            '\x1b[0m', 
            end=' '
        )

### Phi-3 4k

In [34]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


 
 
 English and C AP IT AL IZ ATION 
 
 � � � � � � � 
 show _ to kens False None elif == >= else : two tabs :" " Three tabs : "   " 
 
 1 2 . 0 * 5 0 = 6 0 0 
 
 

#### Llama

In [37]:
hf_token = "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"
# show_tokens(text, "meta-llama/Llama-2-7b-hf") #Gated Model. Need Prior access permission

#### BERT base model (uncased) (2018)

In [19]:
show_tokens(text, "bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

/opt/conda/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

[CLS] english and capital ##ization [UNK] [UNK] show _ token ##s false none eli ##f = = > = else : two tab ##s : " " three tab ##s : " " 12 . 0 * 50 = 600 [SEP] 

#### BERT base model (Cased) 

In [20]:
show_tokens(text, "bert-base-cased")

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

[CLS] English and CA ##PI ##TA ##L ##I ##Z ##AT ##ION [UNK] [UNK] show _ token ##s F ##als ##e None el ##if = = > = else : two ta ##bs : " " Three ta ##bs : " " 12 . 0 * 50 = 600 [SEP] 

#### GPT 2

In [21]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
token_ids = tokenizer(text).input_ids
for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' + 
            tokenizer.decode(t) + 
            '\x1b[0m', 
            end=' '
        )

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]


 
 English  and  CAP ITAL IZ ATION 
 
 � � � � � � 
 show _ t ok ens  False  None  el if  ==  >=  else :  two  tabs :"  "  Three  tabs :  "      " 
 
 12 . 0 * 50 = 600 

 

In [25]:
[x for x in token_ids][:10]

[198, 198, 15823, 290, 20176, 40579, 14887, 6234, 198, 198]

In [26]:
tokenizer.decode([x for x in token_ids][:10])

'\n\nEnglish and CAPITALIZATION\n\n'

#### GPT 4

In [29]:
! pip install tiktoken

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 60.9 MB/s eta 0:00:00


In [33]:
import tiktoken

# Get the encoding for GPT-4
encoding = tiktoken.encoding_for_model("gpt-4")

# Encode text
token_ids = encoding.encode(text)
for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' + 
            encoding.decode([t]) + 
            '\x1b[0m', 
            end=' '
        )



 English  and  CAPITAL IZATION 

 � � � � � � 
 show _tokens  False  None  elif  ==  >=  else :  two  tabs :"  "  Three  tabs :  "     "

 12 . 0 * 50 = 600 

 

#### Flan-T5

In [51]:
show_tokens(text, "google/flan-t5-large")

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

English and CA PI TAL IZ ATION  <unk> show _ to ken s Fal s e None  e l if = = > = else : two tab s : " " Three tab s : " " 12. 0 * 50 = 600  </s> 

## Token Embeddings

In [41]:

from transformers import AutoModel, AutoTokenizer

# Load a tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

# Load a language model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

# Tokenize the sentence
tokens = tokenizer('Hey ! How you doing?', return_tensors='pt')

# Process the tokens
output = model(**tokens)[0]

In [42]:
output.shape

torch.Size([1, 8, 384])

In [43]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
Hey
!
 How
 you
 doing
?
[SEP]


In [44]:
output

tensor([[[-3.4065,  0.0198, -0.0398,  ..., -0.1058, -0.3777, -0.0837],
         [-0.7641,  0.2250,  0.4243,  ..., -0.7211, -0.0580, -0.1155],
         [-0.0681,  0.1169,  0.0617,  ..., -0.1078, -1.3347,  0.3221],
         ...,
         [-0.1399,  0.1319,  0.0781,  ..., -0.8518,  0.2250,  0.9214],
         [-1.3714,  0.1432,  0.2458,  ...,  0.3784, -0.2943, -0.0312],
         [-3.2981,  0.1544,  0.0317,  ..., -0.1812, -0.4086, -0.0431]]],
       grad_fn=<NativeLayerNormBackward0>)

### Text Embeddings (for Sentences and Whole Documents)

In [47]:
# ! pip install sentence_transformers

In [50]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

# Convert text to text embeddings
vector = model.encode("Dont read that blog")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/opt/conda/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [53]:
vector = model.encode("Dont read that blog")
vector.shape

(768,)

In [57]:
vector[:20]

array([ 0.02842747,  0.07551555, -0.02264435,  0.02910579,  0.02903057,
        0.03121672,  0.02235354, -0.01968335, -0.00291807,  0.02245826,
        0.01501281,  0.01791071, -0.02600572,  0.06002513, -0.07260133,
        0.06202994,  0.07325291,  0.01470564, -0.03631008, -0.00818955],
      dtype=float32)

In [59]:
!pip install gensim

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 80.9 MB/s eta 0:00:00ta 0:00:01


In [60]:
import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
# More options at https://github.com/RaRe-Technologies/gensim-data
model = api.load("glove-wiki-gigaword-50")

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



[=================================================-] 99.0% 65.3/66.0MB downloaded

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [62]:
model.most_similar([model['prince']], topn=11)

[('prince', 1.0),
 ('king', 0.8236179947853088),
 ('cousin', 0.7823788523674011),
 ('queen', 0.7821861505508423),
 ('nephew', 0.769256055355072),
 ('eldest', 0.7644566893577576),
 ('son', 0.7642147541046143),
 ('brother', 0.759342610836029),
 ('princess', 0.7434840202331543),
 ('uncle', 0.7239657640457153),
 ('throne', 0.7160079479217529)]

In [63]:
model.most_similar([model['county']], topn=11)

[('county', 1.0),
 ('counties', 0.8836436867713928),
 ('district', 0.8448691368103027),
 ('missouri', 0.808628499507904),
 ('mississippi', 0.8019495606422424),
 ('virginia', 0.7961737513542175),
 ('alabama', 0.7935792803764343),
 ('unincorporated', 0.7919945120811462),
 ('arkansas', 0.7900469899177551),
 ('ohio', 0.7867016196250916),
 ('oregon', 0.7845727205276489)]

In [64]:
model.most_similar([model['district']], topn=11)

[('district', 0.9999999403953552),
 ('county', 0.8448691964149475),
 ('districts', 0.8054964542388916),
 ('provincial', 0.746781051158905),
 ('village', 0.7423917651176453),
 ('central', 0.7314949035644531),
 ('state', 0.7311192750930786),
 ('municipal', 0.7207850813865662),
 ('counties', 0.7162149548530579),
 ('town', 0.7158555388450623),
 ('located', 0.7151240110397339)]

In [65]:
model.most_similar([model['japan']], topn=11)

[('japan', 1.0000001192092896),
 ('japanese', 0.8822371363639832),
 ('china', 0.8428841829299927),
 ('korea', 0.8154973983764648),
 ('tokyo', 0.8078719973564148),
 ('taiwan', 0.7847011685371399),
 ('korean', 0.775836169719696),
 ('asian', 0.7661136984825134),
 ('chinese', 0.7590301632881165),
 ('greece', 0.7550806403160095),
 ('beijing', 0.7429268956184387)]

In [66]:
model.most_similar([model['europe']], topn=11)

[('europe', 1.0000001192092896),
 ('european', 0.881193220615387),
 ('asia', 0.8346829414367676),
 ('world', 0.826363742351532),
 ('countries', 0.8196073770523071),
 ('britain', 0.8159738779067993),
 ('continent', 0.798284649848938),
 ('america', 0.7945005893707275),
 ('germany', 0.7915973663330078),
 ('country', 0.7908257246017456),
 ('united', 0.7725075483322144)]

In [69]:
model.most_similar([model['karnataka']], topn=11)

[('karnataka', 1.0),
 ('kerala', 0.9169433116912842),
 ('nadu', 0.8940614461898804),
 ('andhra', 0.8888077139854431),
 ('odisha', 0.8827202916145325),
 ('pradesh', 0.8745287656784058),
 ('maharashtra', 0.8712483644485474),
 ('rajasthan', 0.8685322999954224),
 ('punjab', 0.8510237336158752),
 ('bihar', 0.8445242643356323),
 ('uttar', 0.8443878293037415)]

In [73]:
model.most_similar([model['israel']], topn=21)

[('israel', 1.0),
 ('israeli', 0.8956456184387207),
 ('palestinians', 0.8649078607559204),
 ('palestinian', 0.86412113904953),
 ('syria', 0.8414742350578308),
 ('gaza', 0.8301867842674255),
 ('lebanon', 0.8250741958618164),
 ('arafat', 0.8130190372467041),
 ('israelis', 0.812950849533081),
 ('jerusalem', 0.8047566413879395),
 ('yasser', 0.7921969294548035),
 ('arab', 0.7893485426902771),
 ('hamas', 0.7889488935470581),
 ('iraq', 0.7836460471153259),
 ('netanyahu', 0.7680053114891052),
 ('palestine', 0.765000581741333),
 ('plo', 0.7639290690422058),
 ('hezbollah', 0.7484215497970581),
 ('jordan', 0.7436054348945618),
 ('withdrawal', 0.7432913780212402),
 ('peace', 0.7375448346138)]